### ISSUE TITLE
Tyler can't commit. 

### ISSUE THREAD

**Issue by T-H-1** [Liiift-Studio/Optical-Font-Website#13]
Example: Typo fix: Disability Aliiance BC spelling commit failed.

**Comment by T-H-1** [comment]
![Screen Shot 2022-04-11 at 8 12 31 AM](https://user-images.githubusercontent.com/55114346/162854844-79c9d100-55a3-49bd-8e85-ab745322ad07.png)

**Comment by quitequinn** [comment]
<img width="1232" alt="Screen Shot 2022-04-11 at 5 36 27 PM" src="https://user-images.githubusercontent.com/2885870/162855255-ad490dcd-3d33-405e-8ed7-d5e8f11c76e8.png">

**Comment by quitequinn** [comment]
On fix lets makesure we dont leave the site in a buggy state.
